SELECT TOP (1000) [Book_Id]
      ,[Publisher_email]
      ,[Author_Names]
      ,[Author_Pseudonym]
      ,[Editor_Name]
      ,[Publication_Title]
      ,[Edition]
      ,[Impression]
      ,[Book_ISBN]
      ,[Set_ISBN]
      ,[Publisher_Name]
      ,[Publisher_Address]
      ,[Publication_Year]
      ,[Price]
      ,[Fiction_Or_NonFiction]
      ,[Genre]
      ,[Publication_langauge]
      ,[English_Title_version]
      ,[Book_Upload]
  FROM [nlsa_db].[dbo].[Book_InformationSheet]